doc/index.rst, doc/whats_new.rst, doc/whatsnew/v0001.txt, doc/whatsnew/v0002.txt, doc/whatsnew/v0003.txt
_Sorry the last pull request was a mistake because I want to merge this into dev and not into master branch._
I would like to add a "what's new" section to the documentation. I got the idea from the pvlib.
Now everybody can add a line to the file of the next version, if something is added, changed, enhanced,...
@oemof/oemof-main : What do you all think about it?
=> add a whats new section the documentation

oemof/tools/helpers.py, tests/constraint_tests.py, tests/lp_files/source_fixed.lp, tests/lp_files/transformer_simp.lp, tests/lp_files/transformer_simp_invest.lp, tests/lp_files/two_inputs_one_output.lp, tests/lp_files/two_inputs_one_output_invest.lp
See the discussion on #137 for details. The changes here make all the tests pass again, at least for me. Have a look at the patches and try it out for yourself. If everything is ok, you can merge the stuff into dev.
=> Merge issue #137 fixes into dev

oemof/solph/blocks.py, oemof/solph/groupings.py, tests/constraint_tests.py, tests/lp_files/max_source_min_sink.lp
At the moment it is good that it has no effect because the InvestmentFlow should also be part of the Flow group. But in the long run it might be useful to understand what happens.
=> Flow groupings has no effect.

examples/oemof_full_check.py, rtd_requirements.txt, tests/lp_files/fixed_source_invest_sink.lp, tests/lp_files/fixed_source_variable_sink.lp
Tests broke for pyomo >= 0.5. This PR will try to fix it.
=> Fix tests for pyomo >= 0.5

doc/whatsnew/v0-1-2.rst, oemof/solph/inputlib/csv_tools.py
this functionalities allows preprocessing of multiple csv files that are merged into one. We might incoporate this for later usage inside the NodesFromCSV function...
=> Add function to solph inputlib for merging multiple csv-files

doc/whatsnew/v0-1-2.rst, oemof/solph/models.py, oemof/solph/options.py
Accessing investment result is really annoying right now as they are located shitty. I propose adding an investment object to result dict for easier access. I know we wanted to replace the result dict anyway in future but until then... who knows
=> Add investment dict to results object for easier access

oemof/outputlib/__init__.py
With this PR it will be possible to instantiate an outputlib.ResultsDataFrame not only from an energy-system but also from a csv-result-file.
=> read ResultsDataFrame from file

oemof/outputlib/processing.py
Just removes empty decision vars..
=> Fix error in outputlib

doc/oemof_solph.rst, doc/whatsnew/v0-2-0.rst, oemof/outputlib/graph_tools.py, oemof/outputlib/processing.py, oemof/solph/__init__.py, oemof/solph/blocks.py, oemof/solph/components.py, oemof/solph/models.py, tests/constraint_tests.py, tests/lp_files/fixed_source_invest_sink.lp, tests/lp_files/fixed_source_variable_sink.lp, tests/lp_files/invest_source_fixed_sink.lp, tests/lp_files/linear_transformer.lp, tests/lp_files/linear_transformer_chp.lp, tests/lp_files/linear_transformer_chp_invest.lp, tests/lp_files/linear_transformer_invest.lp, tests/lp_files/max_source_min_sink.lp, tests/lp_files/storage.lp, tests/lp_files/storage_invest.lp, tests/lp_files/transformer.lp, tests/lp_files/transformer_invest.lp, tests/lp_files/variable_chp.lp, tests/regression_tests.py, tests/test_installation.py, tests/test_scripts/test_solph/test_flexible_modelling/test_add_constraints.py, tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py, tests/test_scripts/test_solph/test_simple_dispatch/test_simple_dispatch.py, tests/test_scripts/test_solph/test_storage_investment/storage_investment2.py, tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py, tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py
I decided for just Model, I think we can still rename it, once we actually have more models. 
Please approve..(see discussion: #354 )
=> Rename OperationalModel to Model

oemof/outputlib/processing.py, oemof/solph/components.py, tests/test_scripts/test_solph/test_generic_chp/ccet.csv, tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py
Some formatting and the a fix for minimum flue gas losses!
=> Improve GenericCHP

doc/using_oemof.rst
@gnn or @uvchik please check :) Thanks!
=> Revise text for feedinlib

oemof/solph/custom.py
I am not sure, but I think  / hope this functionality is not included in the transformer already...as for the lopf there is an link example an the branch with the same name in the example repository
=> Add Link component and block

README.rst, doc/about_oemof.rst
I would also like to add something like this on the first page of oemof.org. 
What do you think? Who can I ask for proofreading?
=> Mini guide for contribution

doc/installation_and_setup.rst
I removed a paragraph describing python package installation because it's not very interesting for the oemof documention.
=> Remove additional python package description

oemof/outputlib/graph_tools.py, oemof/solph/models.py, tests/test_scripts/test_solph/test_flexible_modelling/test_add_constraints.py, tests/test_scripts/test_solph/test_simple_dispatch/test_simple_dispatch.py
Hey I like to restructure solph models internally, to add a multi-period model at some point, which I won't merge with the existing stuff. I think this will add flexibility...
Does not change anything really for anyone except core-solph-developers ;)
I really like to merge this once for v0.2 ;)
@gnn : Would be very interested in your opinion on my code!
=> Add BaseModel to solph 

doc/developing_oemof.rst
I added the github guidelines and restructured advices.
=> Revise collaboration with pull requests

doc/oemof_outputlib.rst, doc/using_oemof.rst
I corrected a detail in the docu "Using oemof". The pandas object we use is a pandas dataframe, not a MultiIndex dataframe.
=> Correct desctribtion of pandas Dataframe

oemof/solph/components.py, oemof/solph/custom.py, tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py, tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py, tests/test_scripts/test_solph/test_generic_offsettransformer/test_generic_offsettransformer.py
Opened in favor of https://github.com/oemof/oemof/pull/349
=> Improve GenericCHP component

doc/whatsnew/v0-2-0.rst
This adds an extra chapter for new components within WHATSNEW. Feel free to merge if you are fine!
=> Add WHATSNEW for new components

oemof/tools/console_scripts.py, setup.py, tests/basic_tests.py, tests/constraint_tests.py, tests/regression_tests.py, tests/solph_tests.py, tests/test_components.py, tests/test_console_scripts.py, tests/test_network_classes.py, tests/test_processing.py, tests/test_scripts/test_solph/test_connect_invest/test_connect_invest.py, tests/test_scripts/test_solph/test_flexible_modelling/test_add_constraints.py, tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py, tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py, tests/test_scripts/test_solph/test_generic_offsettransformer/test_generic_offsettransformer.py, tests/test_scripts/test_solph/test_simple_dispatch/test_simple_dispatch.py, tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py, tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py, tests/test_solph_network_classes.py, tests/tool_tests.py
Keep release branch up-to-date
=> Merge new commits from dev to release branch

oemof/outputlib/views.py
* Describe your pull request as transparent as possible
Adds the possiblity to return dataframe with multiindex column / index for a view
=> Add option for multiindex dataframe on view

doc/whatsnew/v0-2-1.rst, setup.py
=> Merge updated dev into release_0.2.1

oemof/solph/components.py
Just moves code to method, as subclassing was kind of diffcult, when so many things are going on inside the __init__
Please approve ;-)
=> Move flow creation in storage to method

oemof/outputlib/processing.py, oemof/solph/components.py, oemof/solph/custom.py, oemof/solph/groupings.py, oemof/solph/network.py
**Description**
* Adds methods for easier coupling between solph classes and their constraints.
* Only changes internal solph logic
* Two test that fail need to be adapted
=> Add constraint group methods to solph classes

.coverall.yml, .travis.yml, README.rst
* Describe your pull request as transparent as possible
* What functionality does it implement?
* Where is it located?
* How does the API look?
...
* Related issues?
* Share your knowledge: Insights/Remarks
* Other comments and questions
* [] For new features: Remember the documentation!
=> add coveralls

oemof/solph/components.py, tests/constraint_tests.py, tests/lp_files/connect_investment.lp, tests/lp_files/investment_limit.lp, tests/lp_files/storage.lp, tests/lp_files/storage_invest_2.lp, tests/lp_files/storage_invest_4.lp, tests/lp_files/storage_invest_5.lp, tests/lp_files/storage_invest_6.lp, tests/test_components.py, tests/test_scripts/test_solph/test_storage_investment/test_invest_storage_regression.py
=> add existing flow-investment to capacity-flow constraint

tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
Fix issue #474.
Conversion factor gets lost after dump/restore.
=> Fixe/issue #474

oemof/solph/components.py, tests/constraint_tests.py, tests/lp_files/storage_invest_minimum.lp
=> Fix bug #559

oemof/solph/blocks.py
=> Fix/issue #563

oemof/groupings.py, oemof/network.py, tests/test_groupings.py, tests/test_network_classes.py
The test coverage of these modules is a bit on the low side, so this branch collects some additional tests improving it.
=> Improve `groupings` and `network` coverage

doc/developing_oemof.rst, doc/oemof_outputlib.rst
This PR is for improving the documentation, especially the outputlib.
Uwe made the suggestion to structure the documentation of the outputlib in more or less two parts. I made a first attempt. Any comments, suggestions, reviewing are very welcome.
Please feel free to directly commit your improvements!
Related issues: #500 #550 ...
=> Improve (outputlib) documentation

VERSION, doc/whats_new.rst, doc/whatsnew/v0-3-1.rst, doc/whatsnew/v0-3-2.rst, oemof/__init__.py, oemof/outputlib/processing.py, oemof/solph/models.py, tests/test_models.py
In my opinion the results handling in the BaseModel is confusing, so I would like to change it.
1. The solver-results (see below) are written to the `results` attribute of the EnergySystem object.
I could not find it in the documentation that the solver-results can be found there and I wonder why the main results (results of the variables) cannot be found there. We should discuss if we want the results written back in the EnergySystem or not. If we want to keep it as it is, we should at least rename the attribute from `results` to `solver_results`.
Normally I go this way:
```python
[...]
model = solph.Model(energysystem)
model.solve()
energysystem.results['main'] = model.results()
energysystem.results['meta'] = outputlib.processing.meta_results(model)
energysystem.dump(dpath=something, …
```
=> Revise results handling in the BaseModel

doc/whatsnew/v0-3-2.rst, oemof/outputlib/processing.py, oemof/solph/models.py, tests/test_models.py
Sorry I mixed up between dev and v0.3, but I hope this will fix it again.
=> Fix merge chaos

.travis.yml
=> Improve dependency integration in Travis

README.rst, oemof/network.py, oemof/outputlib/processing.py, oemof/solph/components.py, oemof/solph/custom.py, oemof/solph/groupings.py, oemof/solph/network.py, oemof/tools/console_scripts.py, oemof/tools/logger.py
Integrate lgtm and fix obvious alerts.
=> Integrate lgtm

.coveragerc, .travis.yml, doc/api/oemof.tools.rst, setup.py
* After removing datapackage from the oemof package we forgot some fragments.
* Add requirements for developers
* Update versions of requirements
=> Remove unused datapackage fragments and update setup.py

doc/about_oemof.rst, doc/getting_started.rst, doc/oemof_outputlib.rst, doc/oemof_solph.rst, doc/using_oemof.rst
Fix some AE/BE typos in the 'getting_startet' and creating pull request for test purpose
=> Fix/review doc - fix some AE/BE typos

oemof/outputlib/__init__.py, oemof/solph/__init__.py, oemof/tools/__init__.py
This is just a little coding style change as suggested by LGTM. It replaces module self imports by relative imports of the corresponding dependencies.
=> Replace self-imports (coding style fix)

docs/usage.rst
Corrected minor spelling error in the docs for usage.rst
=> Minor spelling error in the docs

docs/whatsnew/v0-4-1.rst, setup.py, src/oemof/solph/custom.py, src/oemof/solph/models.py
There seems to be an (undocumented) change to Pyomo's API. (They never provide a changelog, so one might argue, every change is undocumented.) This commit allows to live with the issue.
Testing would require using different versions on Pyomo, and it would require testing to find out which version introduced the change.
Fix #709
=> Fix SolverStatus and '_bound' problem of pyomo 5.7.0

oemof/solph/components.py
Related issues #597 
- sets are removed from `GenericStorage` and `GenericInvestmentStorage`
- table is added to `GenericStorage` and  `OffsetTransformer` 
- some small changes for the length of the "===" in tables
=> update docstrings of some classes in components.py

src/oemof/solph/blocks.py
* Update formulation of constraint (no more division)
* Use symbols insted of textual varaible names in formulas
* Add table of varables
=> Update transformer docstring

CONTRIBUTING.rst, README.rst, docs/_logo/logo_oemof_solph_big.svg, docs/_logo/logo_oemof_solph_big_editable_font.svg, docs/_logo/logo_oemof_solph_mid.svg, docs/_logo/logo_oemof_solph_mid_editable_font.svg, docs/_logo/logo_oemof_solph_small.svg, docs/_logo/logo_oemof_solph_small_editable_font.svg, docs/usage.rst, src/oemof/solph/constraints.py
Revise the [README](https://github.com/oemof/oemof-solph/tree/docs/improve-readme) file:
=> Revise README

setup.py
Resolve #726 
Links to the oemof-solph docu were incorrect as well.
=> Fix links for changelog and issue tracker

CONTRIBUTING.rst
Basically as said in the title.
=> [docs]: Add info on available tox environments

docs/reference/oemof.solph.rst, src/oemof/solph/flows/_flow.py
Related to #772.
Docstring for the Flow class (without InvestmentFlow, NonConvexFlow)
=> Revise docstring of flow class

src/oemof/solph/buses/_bus.py
Related to #772.
Docstring for the Bus class
=> Revise docstring of Bus class

src/oemof/solph/processing.py
pandas.DataFrame.append is deprecated
=> Fix pandas FutureWarnings

examples/nonconvex_invest_flow_examples/diesel_genset_nonconvex_investment.py
Based on the new structure of the flows, the example representing a combination of the NonConvex and Investment options for a diesel genset in a hybrid mini-grid has been slightly modified.
=> Feature/restucture flow -- update the example

src/oemof/solph/custom/link.py, tests/constraint_tests.py, tests/lp_files/link.lp
Removes nonfunctional constraints 2 and 3 from link.
=> Remove limit_direction and related constraints

src/oemof/solph/components/_source.py, tests/constraint_tests.py, tests/lp_files/flow_invest_with_offset.lp, tests/lp_files/flow_invest_with_offset_no_minimum.lp, tests/test_components.py, tests/test_warnings.py
This PR makes kwargs explicit for component Source.
=> Make kwargs explicit for Source component

AUTHORS.rst, docs/whatsnew/v0-5-0.rst, examples/flow_count_limit/flow_count_limit.py, setup.py, src/oemof/solph/_helpers.py, src/oemof/solph/_options.py, src/oemof/solph/components/_generic_chp.py, src/oemof/solph/components/_sink.py, tests/test_components.py, tests/test_scripts/test_solph/test_generic_chp/ccet.csv, tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py
now, with better branch name according to @gnn ;-)
Based on multiple discussions, see Issue: ...
Fixes #729
=> Make kwargs explicit

docs/conf.py, examples/invest_nonconvex_flow_examples/diesel_genset_nonconvex_investment.py, examples/storage_investment/v1_invest_optimize_all_technologies.py, examples/time_index_example/time_index_example.py, setup.py, src/oemof/solph/_models.py, src/oemof/solph/components/_generic_storage.py, src/oemof/solph/components/experimental/_generic_caes.py, src/oemof/solph/components/experimental/_sink_dsm.py, src/oemof/solph/constraints/flow_count_limit.py, src/oemof/solph/constraints/integral_limit.py, src/oemof/solph/constraints/investment_limit.py, tests/constraint_tests.py, tests/test_scripts/test_solph/test_storage_investment/test_invest_storage_regression.py, tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py
Fixes #905
I have the feeling that the problems have been solved in Numpy/Pandas.
=> Remove upper bound for Numpy

src/oemof/solph/components/_generic_storage.py
Adds custom_attributes (dictionary) to GenericStorage in the same way, other components also have them.
Implements #906
=> Add custom_attributes to GenericStorage

src/oemof/solph/_energy_system.py, src/oemof/solph/_models.py, src/oemof/solph/components/_generic_storage.py, src/oemof/solph/components/experimental/_sink_dsm.py, src/oemof/solph/flows/_investment_flow_block.py, src/oemof/solph/processing.py, tests/multi_period_constraint_tests.py, tests/test_energy_system.py, tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_dispatch_model.py, tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_investment_model.py
A list should easier to handle compared to a dictionary using integers counting from 0 as keys.
=> Use list to describe periods

src/oemof/solph/_models.py
Closes #1002 by implementing a loop over all energy systems passed to the model class.
=> make BasicModel consider all constraint groups

examples/basic_example/basic_example.py
These minor issues will in my opinion make it easier to understand the Basic example. 
Closes #1025
=> Improve structure and fix some minor things of Basic example

setup.py
=> Fix oemof network requirement

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/tox_pytests.yml, CONTRIBUTING.rst, examples/cellular/cellular.py, examples/dual_variable_example/dual_variable_example.py, pyproject.toml, setup.cfg, src/oemof/solph/_console_scripts.py, src/oemof/solph/_energy_system.py, src/oemof/solph/components/_generic_chp.py, src/oemof/solph/components/_link.py, src/oemof/solph/components/_offset_converter.py, src/oemof/solph/components/experimental/_piecewise_linear_converter.py, src/oemof/solph/components/experimental/_sink_dsm.py, src/oemof/solph/constraints/equate_variables.py, src/oemof/solph/constraints/integral_limit.py, src/oemof/solph/constraints/investment_limit.py, src/oemof/solph/constraints/shared_limit.py, src/oemof/solph/processing.py, src/oemof/solph/views.py, tests/test_options.py, tox.ini
=> Replace the specification of frequency for hours in pandas data_range

examples/basic_example/basic_example.py
There were some misnamed variables, probably introduced by "AI programming". I fixed them.
Closes #1070
=> Fix non-existing variable names

.github/workflows/packaging.yml
=> Change version from v2 to v4 for artifact upload

docs/_files/GenericCHP_darkmode.svg, docs/basic_concepts.rst, docs/basic_concepts/buses.rst, docs/basic_concepts/components.rst, docs/basic_concepts/energy_system.rst, docs/basic_concepts/flows.rst
Add a few darkmode versions of existing figures.
=> Contribution to refactoring of the Docs

docs/introductory_tutorials.rst, docs/introductory_tutorials/tutorial_1.rst, docs/introductory_tutorials/tutorial_2.rst, docs/introductory_tutorials/tutorial_3.rst, docs/introductory_tutorials/tutorial_4.rst
Content still needs to be added.
=> Add basic examples pages to new docs layout

tutorials/introductory/ev_charging.py
First idea of using simple dynamic prices. I used only three different prices/gain to be still able to understand what the solver does. Do you want to add real dynamic prices?
=> add dynamic prices

examples/storage_investment/v1_invest_optimize_all_technologies.py, examples/storage_investment/v2_invest_optimize_only_gas_and_storage.py, examples/storage_investment/v3_invest_optimize_only_storage_with_fossil_share.py, examples/storage_investment/v4_invest_optimize_all_technologies_with_fossil_share.py
This PR should provide a few adjustments to the inline documentation of the GenericInvestmentStorage usage.
Closes #1022
=> Improve documentation of examples for GenericStorage with Investment

.github/workflows/lint.yml, .github/workflows/packaging.yml, .github/workflows/tox_checks.yml, .github/workflows/tox_pytests.yml, src/oemof/solph/components/_generic_storage.py, tests/test_scripts/test_solph/test_invest_fix_flow/test_simple_invest_fixed.py, tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch.py, tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch_one.py, tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch_one_explicit_timemode.py, tests/test_scripts/test_solph/test_simple_model/test_simple_invest.py
Fixes #1185 (but with inconsistent definition of storage content indexing).
=> Consider storage_costs for storage with capacity investment in v0.5

examples/subnetwork/subnetwork_example.py, pyproject.toml, src/oemof/solph/buses/_bus.py, src/oemof/solph/components/_converter.py, src/oemof/solph/components/_extraction_turbine_chp.py, src/oemof/solph/components/_generic_chp.py, src/oemof/solph/components/_generic_storage.py, src/oemof/solph/components/_link.py, src/oemof/solph/components/_offset_converter.py, src/oemof/solph/components/_sink.py, src/oemof/solph/components/_source.py, src/oemof/solph/components/experimental/_generic_caes.py, src/oemof/solph/components/experimental/_piecewise_linear_converter.py, tests/test_processing.py
=> Add subnetwork functionnality
