oemof/oemof-solph

- doc/api/oemof.tools.rst
- examples/development_examples/example_app.py
- oemof/solph/linear_constraints.py
- oemof/solph/optimization_model.py
- oemof/tools/helpers.py
- oemof/tools/logger.py
Therefore we have to be sure that  at least a basic logger is defined otherwise there won't appear anything on the screen. So I defined a very basic logger to see the message on the screen.
It is still possible to use the default oemof logger described  in issue #28.
The advantage is that you can see the message on the screen and(!) in the file. Furthermore it is configurable so that you can decide what level you want to see, and what level you want to log in a file.
See the following link for more information: https://docs.python.org/3/howto/logging.html
@oemof/oemof-main : Is it okay to merge it?
> Replace print by logging.info

- doc/whatsnew/v0-0-5.rst
- oemof/core/network/entities/components/transformers.py
- oemof/solph/linear_constraints.py
- oemof/solph/optimization_model.py
- oemof/solph/predefined_objectives.py
- oemof/tools/create_components.py
- oemof/tools/helpers.py
- tests/constraint_tests.py
- tests/lp_files/two_inputs_one_output.lp
- tests/lp_files/two_inputs_one_output_invest.lp
The PostHeating class was created to describe a instantaneous flow heater. The new idea is describe a more generic class that describes a general transformer that has two inputs and one output.
This transformer can represent a heat pump, an instant flow heater or any other component with two inputs and one output.
See issue #114 for more information
> Refactor the PostHeating class and its solph functions

- examples/example_tests.py
- examples/solph/simple_least_costs/simple_least_costs.py
- examples/solph/storage_optimization/storage_invest.py
- oemof/outputlib/__init__.py
The name of the keyword is not important to me so change it if you want.
I renamed the keyword of the results DataFrame from `input` to `tobus` and from `output` to `frombus` to make it a bit more intuitive. See #190 for more details.
**Before:**
```python
input_into_pp_gas = myresults.slice_by(obj_label='pp_gas', type='output')
output_from_pp_gas = myresults.slice_by(obj_label='pp_gas', type='input')
```
**Now:**
```python
input_into_pp_gas = myresults.slice_by(obj_label='pp_gas', type='frombus')
output_from_pp_gas = myresults.slice_by(obj_label='pp_gas', type='tobus')
```
> Fix issue 190

- examples/solph/csv_reader/investment_example.py
- examples/solph/flexible_modelling/add_constraints.py
- examples/solph/simple_least_costs/simple_least_costs.py
- examples/solph/storage_optimization/storage_invest.py
- oemof/energy_system.py
- oemof/outputlib/__init__.py
- oemof/solph/models.py
- tests/basic_tests.py
- tests/constraint_tests.py
- tests/regression_tests.py
@simnh wrote:
> We should fix this at is kind of confusing because inside the examples and the OperationalModel class we use 'time_index' whereas inside EnergySystem class we use 'time_idx'...
> Clearfiy API oemof core: EnergySystem attribute time_idx -> time_index

- oemof/tools/logger.py
- When installed via pip no VERSION file available in
virtualenvs/oemof__release_v0.1/lib/python3.4/site-packages/oemof/
- Fix is maybe slow due to import of whole oemof package, but it's easy
(:
> Fix "get version number in logging"

- doc/whatsnew/v0-1-2.rst
- oemof/solph/inputlib/csv_tools.py
At one point we might also just use ad dictionary with keys for specific attributes: 
```
addtional_attributes = {'flow': [], 'seq': [], 'bus' =[]} 
```
But this would change the API, so for now just adding an attribute
> Features/addtional flow attributes in NodesFromCSV

- oemof/outputlib/__init__.py
I have added a method to slice inputs/outputs/other around busses as is seems to be a common subset to be extracted from the RDF.
TODOs:
* Update WHATSNEW
* Check docstrings
Could you check and give some feedback?
> Add method to slice a balance around a bus

- doc/whatsnew/v0-1-2.rst
- oemof/solph/blocks.py
- oemof/solph/network.py
I think it would be faster if the methods are changed to attributes. As I understand it a methods like `_input` will search for the input flow every time it is called. If it is an attribute it will be done once. These attributes are needed when the constraints are build in the blocks module. If we use them inside rules they are called 8760 times (or more). 
Furthermore I do not understand why do use protected methods as we do want to use them in other modules and classes that are not child classes.
> Change structure of network classes

- doc/whatsnew/v0-1-2.rst
- examples/solph/storage_investment/storage_investment.py
- oemof/tools/economics.py
Some economic calculations are frequently used. I added a module to tools as suggested by @uvchik . 
We might want to add calculations based on the results structure of the oemof core layer, e.g. calculating LOC etc.
> Economics module in tools

- oemof/outputlib/__init__.py
This is only a one-liner that removes the levels from the column index when using the newly introduced bus balance slice and should be mergeable directly.
> Remove index levels from column index

- README.rst
- doc/getting_started.rst
* add a hint how to cite oemof according to a question on the user meeting
* add a hint how to download the documentation according to PR #314
> Add hints to the start page (documentation)

- oemof/energy_system.py
- oemof/solph/models.py
I looked at the examples and at the documentation and we only use the datetimeindex inside the EnergySystem so I like to remove it from OM
> Remove datetimeindex from OperationalModel

- doc/installation_and_setup.rst
The simple_least_costs example is not executable in the last oemof version, so I suggest to change it to  simple_dispatch or similar.
> changing simple_dispatch with simple_dispatch

- doc/oemof_solph.rst
- oemof/solph/components.py
- tests/constraint_tests.py
- tests/lp_files/variable_chp.lp
- tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py
I renamed the `VariableFractionTurbine` turbine to `ExtractionTurbineCHP` and the attribute from `conversion_factor_single_flow` to `conversion_factor_full_condensation`.
Any objections?
See: #361.
> rename VariableFractionTurbine and its attribute

- oemof/solph/components.py
- tests/constraint_tests.py
- tests/test_components.py
The default value for the `nominal_input_capacity_ratio` (as well output) is now None.
```diff
self.nominal_input_capacity_ratio = kwargs.get(
- 'nominal_input_capacity_ratio', 0.2)
+ 'nominal_input_capacity_ratio', None)
```
I added some checks that raise errors if the storage is defined contradictory.
`nominal_value` im Flow AND `nominal_input_capacity_ratio` -> AttributeError
`nominal_value` im Flow OR `nominal_capacity`with investment -> AttributeError
Furthermore I wrote some tests and fixed existing ones to test the behaviour above.
TODO:
We could write a good error message to help users to understand what went wrong. At the moment
there are only drafts.
> Make it possible to define the nominal_value of flows directly in the storage definition

- doc/whatsnew/v0-2-0.rst
- oemof/solph/blocks.py
- oemof/solph/components.py
- oemof/solph/constraints.py
- oemof/solph/network.py
- tests/constraint_tests.py
- tests/lp_files/fixed_source_invest_sink.lp
- tests/lp_files/fixed_source_variable_sink.lp
- tests/lp_files/invest_source_fixed_sink.lp
- tests/lp_files/storage.lp
- tests/lp_files/storage_invest.lp
- tests/solph_tests.py
- tests/test_components.py
- tests/test_scripts/test_solph/test_connect_invest/test_connect_invest.py
- tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
- tests/test_solph_network_classes.py
As this attribute is not necessarily needed but might be confusing in investment models we would like to remove it. This came up in PR #396 but I think it is cleaner to create a separate PR.
@oemof/oemof-solph Any objections?
> Remove fixed_costs attribute from Flow class

- README.rst
- doc/developing_oemof.rst
I added a new section on developing in README.txt and extended developing_oemof.rst:
Now there is a welcome sentence to tell about the possibilities to become a developer.
I also expanded section on issues and put it directly under pull requests as those are the two ways to communicate.
Apart from this, I wonder if the section on pull requests still describes the workflow how we understand it now. We could add a bullet point on how to invite reviewers (how many, whom,..) Also, is the section on tests still up to date?
> Improve developer welcome

- oemof/outputlib/processing.py
- oemof/outputlib/views.py
The conversion of the results keys belongs to processing rather than to views.
> move key-conversion-function from views to processing module

- oemof/outputlib/processing.py
- oemof/solph/plumbing.py
- tests/test_processing.py
**Related issue**: #436 
**Located in**: Major change was made to `oemof.solph.plumbing`
**Functionality**:
While building the sequence an internal attribute `self.default_changed` is set to False. Whenever `__getitem__` of sequence is called, only the default value is returned. Before, every time an internal list was extended to requested index. Only, if `__setitem__` is called attribute `self.default_changed` is set to True and an internal list is build, as the sequence no longer consists of only one default value.
**Outcome**:
This revision leads to three things:
1. Testing run-time decreased! (for me, from 8sec to 5sec!) :)
2. `__len__` function of Sequences with only one default value now returns 0 - this is no problem for all tests, but users looking into solph components may get …
> Revision/expanding sequences Sequences with default value get not expanded

- oemof/solph/network.py
With the negative/positive gradient we added dictionaries as attributes to the Flow class.
In the constructor they are named "sequences". I just stumbled over it searching for something else, but naming types correctly make things clearer.
If we have more dictionaries in the future we can distinguish between them within the if statement:
```python
if attribute in dictionaries:
if attribute in typ_a_dictionary:
do something
elif attribute in typ_b_dictionary:
do something else
elif:
....
```
As long as we do have just one type of dictionaries the second if statement is left out.
> change attribut group to dictionary

- oemof/tools/console_scripts.py
- setup.py
- tests/basic_tests.py
- tests/constraint_tests.py
- tests/regression_tests.py
- tests/solph_tests.py
- tests/test_components.py
- tests/test_console_scripts.py
- tests/test_network_classes.py
- tests/test_processing.py
- tests/test_scripts/test_solph/test_connect_invest/test_connect_invest.py
- tests/test_scripts/test_solph/test_flexible_modelling/test_add_constraints.py
- tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py
- tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py
- tests/test_scripts/test_solph/test_generic_offsettransformer/test_generic_offsettransformer.py
- tests/test_scripts/test_solph/test_simple_dispatch/test_simple_dispatch.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
- tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py
- tests/test_solph_network_classes.py
- tests/tool_tests.py
* Describe your pull request as transparent as possible
* Clean code according to developer rules
* Console script added to test oemof including all nosetests and doctests. I did not add anything to the documentation because I think we can test how it works and if it works fine I will add a line there.
* Just use `test_oemof` within your virtual environment.
* I think it should be added it to the v0.2.1 release, because it is mostly code-clean-up and a new hidden function that could be removed in the next release if it does not work as intended. No risk in my opinion :smile:
> Add console test and clean installation test

- doc/whatsnew/v0-2-1.rst
- oemof/network.py
- oemof/solph/custom.py
@ckaldemeyer discovered a bug which meant that `Node`s could not be dumped again after being restored. He discovered this by using `copy.deepcopy` which uses the same protocol as dumping/restoring via `pickle`.
I fixed the issue and would like to have the fix in the next release.
@ckaldemeyer  also made an [example](https://github.com/oemof/oemof_examples/blob/5c120d70f326d8784e7395d22011ea72d5659df0/examples/oemof_0.2/generic_chp/bpt.py) which gets fixed by this branch, so I know my fix works.
> Make deserialized nodes serializable again

- setup.py
This PR will limit the version of each required package in the setup.py to the most actual (working) version for the v0.2.1 release.
The reason is that otherwise pip install oemof will always install the most actual version of each package at the moment of the installation. This behaviour may lead to errors (see #464) if the the API of one required package changed since the last oemof release.
You may check the versions right before the release if I missed an actual important update.
> limit version of required packages to the most actual version

- doc/whatsnew/v0-2-2.rst
- oemof/solph/components.py
The old GenericInvestmentStorageBlock had a fixed Capacity Ratio that had to be initialized and thus you could not solely let oemof invest into the Input/Output Flow.
By adding the if-Statements, it is now possible to have a storage flow that does not influence the capacity of the storage.
> Decouple the investment of storage flows and capacity

- oemof/tools/logger.py
It looks more complicated than it is. I just needed to get the version regardless of the logger. Therefore, I unbundled the functions a little bit. I need this feature, so I would appreciate I quick review.
> make it possible to get version/commit/branch without using the logger

- nose.cfg
- oemof/tools/console_scripts.py
- setup.py
- tests/run_nose.py
- tests/test_console_scripts.py
It does not work if oemof is installed via pip.
Now it can be executed via IDE or console using the python command.
In my opinion this is cleaner. You do not have to use it anyway but it contains all needed parameter.
> move not working console script to test

- oemof/network.py
- tests/test_scripts/test_solph/test_storage_investment/test_invest_storage_regression.py
It should be possible to use tuple and(!) string labels in one EnergySystem. At the moment it is only possible to use either string or tuple labels.
If you mix them you get the following error:
```python
File ".virtualenv/oemof_cosmos/lib/python3.5/site-packages/pyomo/core/base/block.py", line 1314, in component_data_objects sort=sort):
File ".virtualenv/oemof_cosmos/lib/python3.5/site-packages/pyomo/core/base/block.py", line 1244, in _component_data_iter _items = sorted(_items, key=itemgetter(0))
File "oemof/oemof/network.py", line 228, in __lt__
return self.label < other.label
```
> Change existing test to make it fail

- doc/oemof_solph.rst
The example of the ExtractionTurbineCHP has been fixed  (#526 ).
In the code-example of the ExtractionTurbineCHP (in the documentation, section solph-components) the argument name has been corrected. The same name has been corrected in the text below the code-example.
> Fix ExtractionTurbineCHP example in docu

- tests/test_processing.py
It's really simple. The tests weren't fully updated to take a renamed function into account and the resulting deprecation warning messed up the test output. The PR really only renames the old function call to the new one.
> Squelch deprecation warning when testing processing

- oemof/solph/blocks.py
- oemof/solph/options.py
This PR implements the functionality of adding operation cost independently from the output at each time interval. As a result, opr_cost can be now attributed the NONCONVEX_FLOW objects which occur whenever the status of nonconvex flow is 1, otherwise they are 0. 
For me, this functionality was practically useful when modelling e.g. DieselGenerator (DG), as it allowed me to add fix operation cost in case the DG-component is running.
Changes are made to oemof/solph/blocks.py and oemof/sopf/options.py
What do you _think?
> Add operation cost independent from output to NONCONVEX_FLOW

- .coveragerc
- doc/whatsnew/v0-3-0.rst
- oemof/energy_system.py
- oemof/solph/custom.py
- oemof/solph/models.py
- tests/test_models.py
- tests/test_network_classes.py
- tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch_one.py
There are some special conditions in this module and we should remove them or test them.
Furthermore `custom.py` is removed from the test coverage check, because we announced that it is not necessary to write tests for the custom components but we should warn users about this.
> Increase test coverage of solph.models module

- oemof/energy_system.py
- oemof/solph/blocks.py
- oemof/solph/plumbing.py
Setting single values of a sequence leads to unwanted behaviour (e.g. never ending loop). Therefore, I think it is better to allow only the full replacement of a sequence but not the change of single values.
@oemof/oemof-developer-group : Does anybody needs this method???
> Remove __setitem__ because this is not intended

- oemof/solph/components.py
- tests/constraint_tests.py
- tests/lp_files/storage_invest_minimum.lp
Minimum attribute of investment object should be the lower bound of the investment variable.
See #559
> Fix bug #559

- oemof/solph/components.py
* Conditions for Eqs. (10), (11) are now explained closer by.
* Added missing variables "n" in table of symbols.
* Removed the explicit naming of the sets.
(Seems to be more confusing then helpful, see #493.)
> Adjust documentation of GenericCHPBlock

- oemof/energy_system.py
**Describe your pull request as transparent as possible**
* Add subnodes (in list or array like objects of the energy system) to the energy system automatically. 
Useful functionality for individual modelling based on oemof solph base classes like in oemof-
> Add subnodes list when adding objects to energy system instance

- oemof/tools/economics.py
- tests/tool_tests.py
* Describe your pull request as transparent as possible:
The annuity function in the economics tool has been supplemented by possible multiple investment and cost decreases. Both parameters  ('u', 'cost_decrease') can be set optionally. If not set, the function works as before.
* Related issues:
The function was suggested by a user on the last user meeting: https://github.com/baumconsult/gridcon/blob/master/economics_BAUM_171221.py
This is now the output of the working group from the last developer meeting.
This issue #431 might also be related.
> Improve annuity calculation in economics tool

- doc/oemof_solph.rst
- oemof/solph/components.py
I changed the docstring of the two Blocks Extraction Turbine and GenericCHP according to Issue #544:
- time dependences and numbering where it was missing
- the tables were changed (new column anda new order)
- sets are removed
I'm sorry for the numerous commits, I had some trouble with my branches.
> Improve documentation of Extraction Turine and GenericCHP

- README.rst
* Add link to ESR paper "The Open Energy Modelling Framework (oemof)"
* Place prominent zenodo doi badge
Implements #571
> Improve hints how to cite oemof

- oemof/solph/components.py
- tests/test_components.py
The deprecated attributes will be silently ignored. This may lead to an unwanted behavior if users have updated from v0.2.3 to v0.3.0. The error message will help to avoid problems.
The following Storage will work with v0.2.3 as well as with v0.3.0 but some attributes will be ignored, so that the capacity of the storage at time step 0  will be `None` and not `0` as intended because the parameter `initial_capacity` does not exists in v0.3.0 and therefore will be ignored. The parameter `initial_storage_level` (new name of `initial_capacity`) will be set to the default value, which is `None`.
```python
storage = solph.components.GenericStorage(
label='storage',
inputs={bel: solph.Flow()},
outputs={bel: solph.Flow()},
capacity_loss=0.5,
initial_capacity=0,
invest_relation_input_capacity=1/6, …
```
> Raise an AttributeError if deprecated attribute is used

- doc/whatsnew/v0-3-1.rst
- doc/whatsnew/v0-3-2.rst
- oemof/solph/constraints.py
- tests/constraint_tests.py
- tests/lp_files/emission_limit.lp
This PR implements a generalised version of "emission_limit", as suggested in #585. As this type of limit implements weighted integrals over the flows, I called it `generic_integral_limit`.
Note that `investment_limit` handles `Flow`s as well as `GenericInvestmentStorage`, so it needs a different treatment. It might be possible to incorporate all of these into one creator function for global limit constraints, but that would then need to work on `Node`s instead of specialised implementations.
> Generalise shared limits

- .travis.yml
This is just an improvement to the TravisCI pipeline, that will hopefully prevent errors like the one mentioned in https://github.com/oemof/oemof/pull/632#issuecomment-542277361.
Background: Before this PR, sudo was used to explicitly call "apt-get install coinor-cbc". However, Travis has an own API to tell the CI pipeline which dependencies have to be installed. Using this officially supported way will hopefully prevent failures when installing cbc.
> Improve dependency integration in Travis

- doc/api/oemof.tools.rst
- oemof/tools/economics.py
Fixes the docstring of oemof.tools.economics.annuity, which has a bug. The formulas are not shown correctly (#688).
Insights: The r in front of the docstring was missing. Also indented the formulas and wrapped the variables described in words with a latex \text{}.
> Fix docstring formulas

- doc/installation_and_setup.rst
I just installed oemof and the cbc solver on my mac and it worked out of the box. Thus I want to remove the remark, that it is not tested yet. On the way I tried to conform the installation instructions for mac to the scheme which is used for Windows and Linux.
> Add confirmed mac installation instructions

- docs/conf.py
Our changelog contains so many links to GitHub issues and pull requests that checking them all locally causes GitHub do respond with a 429 error because of too many requests, but the requests from Travis seem to be whitelisted. So this PR is about finding a way to disable requests to the most frequented URLs when testing locally, but keeping everything switched on when building on Travis.
> Disable GH PR and issue link checks outside of Travis

- oemof/solph/blocks.py
Adapted constraint for comparison of input and output flows with
conversion factors to allow zero values.
By now, setting a conversion factor of "0" to a transformer leads to an zero-division-error due to following part in constraints (`oemof.solph.blocks.Transformer._create()._input_output_relation()`:
```
lhs = (m.flow[i, n, t] / n.conversion_factors[i][t])
rhs = (m.flow[n, o, t] / n.conversion_factors[o][t])
...
block.relation.add((n, i, o, t), (lhs == rhs))
```
I simply switched conversion factors and avoid the zero-division-error!
```
lhs = (m.flow[i, n, t] * n.conversion_factors[o][t])
rhs = (m.flow[n, o, t] * n.conversion_factors[i][t])
...
block.relation.add((n, i, o, t), (lhs == rhs))
```
Results stay the same, only lp-file tests are failing.
I wanted to discuss this before I …
> Allow conversion factor of zero for transformer

- src/oemof/solph/components.py
- src/oemof/solph/custom.py
- src/oemof/solph/groupings.py
- src/oemof/solph/network.py
- src/oemof/solph/processing.py
- tests/constraint_tests.py
- tests/solph_tests.py
- tests/test_components.py
- tests/test_scripts/test_solph/test_connect_invest/test_connect_invest.py
- tests/test_scripts/test_solph/test_flexible_modelling/test_add_constraints.py
- tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py
- tests/test_scripts/test_solph/test_generic_chp/test_generic_chp.py
- tests/test_scripts/test_solph/test_invest_fix_flow/test_simple_invest_fixed.py
- tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch_one.py
- tests/test_scripts/test_solph/test_simple_model/test_simple_invest.py
- tests/test_scripts/test_solph/test_storage_investment/test_invest_storage_regression.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py
- tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py
- tests/test_solph_network_classes.py
- tests/test_warnings.py
As network/tools, etc. are now third party libraries, tox complains about the order of import. This PR fixes the import order.
> Fix import order

- src/oemof/solph/processing.py
- tests/test_scripts/test_solph/test_piecewiselineartransformer/test_piecewiselineartransformer.py
This addresses https://github.com/oemof/oemof-solph/pull/592#pullrequestreview-566257556
In processing.py, a private class had been imported from pyomo.core.base.piecewise. This is now replaced by an import of the public class IndexedPiecewise.
> Replaced private class import with public one

- src/oemof/solph/blocks/non_convex_flow.py
- src/oemof/solph/custom/sink_dsm.py
- src/oemof/solph/network/flow.py
- src/oemof/solph/options.py
- tests/constraint_tests.py
- tests/lp_files/dsm_module_DIW_invest.lp
- tests/lp_files/dsm_module_DLR_invest.lp
- tests/lp_files/dsm_module_oemof_invest.lp
- tests/lp_files/source_with_nonconvex_gradient.lp
This one adds some minor improvements to the SinkDSM formulation:
* Extend the checks of infeasible attribute combinations
* Fix the minor bug in the objective_value formulation for `approach="DIW"`, mentioned in #761
* Improve (consistency and hopefully readability) of code formatting
* Add constraint tests for the investment modeling implemented 
Resolves #761
I guess there is no need to adapt anything in the changelog since it is only some minor fixes and reformatting.
> Improve SinkDSM formulation (formatting, fixes, tests)

- src/oemof/solph/blocks/flow.py
- src/oemof/solph/network/flow.py
- tests/constraint_tests.py
- tests/flow_tests.py
- tests/lp_files/source_with_gradient.lp
- tests/test_processing.py
Adding gradient costs e.g. `negative_gradient={"costs": 12}` will make the optimisation problem infeasible. Fixing the bug wil not help, because the costs are implemented wrongly.
This PR will remove the gradient costs but we can open a new PR afterwards to reimplement them in a clean way.
> Remove gradient costs due to bugs and implementation errors

- docs/whatsnew/v0-5-0.rst
- src/oemof/solph/_options.py
- src/oemof/solph/flows/_non_convex_flow.py
- tests/constraint_tests.py
- tests/lp_files/inactivity_costs.lp
The newly added `inactivity_costs` explicitly model potential costs of non-operation. This might be applicable if degradation is faster when not operating a device. Previously, this could only be expressed implicitly, by giving negative values for the complementary `acitivity_costs`.
PS: This feature was originally proposed at openmod to model [startup_costs dependent on time since last run](https://forum.openmod.org/t/startup-costs-dependent-on-time-since-last-run/2937). When the costs rise linearly, this directly translates to `inacitivity_costs`.
> Add inicativity_costs to NonConvex

- src/oemof/solph/components/experimental/_link.py
The __init__ of the Link component asserts that 2 inputs, outputs and conversion factors are passed. However, some users might want to initialize without passing those, setting them later. This is what oemof.tabular tries to do - and fails. The PR aims to fix that by converting the assertion into a SuspiciousUsageWarning which can be silenced.
Related: https://github.com/oemof/oemof-tabular/pull/21#issuecomment-1058331661
> Convert Link assertion into SuspiciousUsageWarning

- src/oemof/solph/custom/sink_dsm.py
- tests/constraint_tests.py
- tests/test_scripts/test_solph/test_piecewiselineartransformer/test_piecewiselineartransformer.py
Black tests failed for new PRs due to already existing errors.
Simply run `black .` on top level.
> Fix black test failing

- src/oemof/solph/processing.py
When processing results, function `processing.parameter_as_dict()` should return scalars and sequences of given ES. Within the function is a check for methods (aka a check for `callable()`) which shall not be included in parameter dict. Nevertheless, the check was implemented incorrect, resulting in methods to go into parameter dict. This PR fixes that.
Fixes #707 
Error was related to check outcome of `dir(component)` for callables. But as `dir()` returns list-of-str and str is not callable, methods weren't filtered out.
> Fixed check for callables in processing.parameter_as_dict()

- src/oemof/solph/processing.py
- tests/test_processing.py
This PR adds an option to exclude attributes from `processing.parameter_as_dict()` scan in.
Closes #824
> Add option `exclude_attrs` to processing.parameter_as_dict() 

- setup.py
- src/oemof/solph/_models.py
- src/oemof/solph/buses/_bus.py
- src/oemof/solph/components/_extraction_turbine_chp.py
- src/oemof/solph/components/_generic_chp.py
- src/oemof/solph/components/_generic_storage.py
- src/oemof/solph/components/_offset_transformer.py
- src/oemof/solph/components/_transformer.py
- src/oemof/solph/components/experimental/_generic_caes.py
- src/oemof/solph/components/experimental/_link.py
- src/oemof/solph/components/experimental/_piecewise_linear_transformer.py
- src/oemof/solph/components/experimental/_sink_dsm.py
- src/oemof/solph/flows/_flow.py
- src/oemof/solph/flows/_investment_flow.py
- src/oemof/solph/flows/_non_convex_flow.py
- src/oemof/solph/flows/experimental/_electrical_line.py
- tests/constraint_tests.py
- tests/lp_files/connect_investment.lp
- tests/regression_tests.py
- tests/test_scripts/test_solph/test_piecewiselineartransformer/test_piecewiselineartransformer.py
- tox.ini
At the moment the use of Pyomo >= 0.6 leads to very high computing times ( up to 100 times longer). @gnn found out, that this is caused by the root logger but only if the logging level is DEBUG. The problem is located in the Model class.
1. Therefore I changed the default logger level in oemof.tools to INFO, because the logger from oemof.tools is used in almost every solph example. In some examples the logger is explicitly set to DEBUG, so changing the default value will not help.
2. As it is also possible to set the logger in a different way, I added a function to check the level of the logger in the Model class. Now an exception will be raised if the root logger level is set to DEBUG (default. WARNING). This exception can be avoided if the model is initialised using `debug=True`: `model …
> Make solph work with pyomo >= 0.6

- src/oemof/solph/custom/link.py
This PR aims to merge PR #827, which was merged into v0.5, into dev as well.
This PR only turns errors into a warning - should be fine to merge.
> Refactored assertion error in Link component into suspicious warning

- src/oemof/solph/custom/link.py
Related issue: #837 
This PR adds an option `limit_direction` to Link component in order to suppress creation of flow constraints regarding link direction.
As option defaults to `True`, this should not effect current setup, but only enables other devs to disable mentioned feature.
> Added option to (un-)limit directions in Link component

- setup.py
- tests/test_models.py
- tests/test_warnings.py
Set stable release of oemof.network as requirement. As the stable release emits a FutureWarning when the deprecated Node/Entity.registry is used, the warning has to be silenced when testing for other warnings.
Note that out unit tests use the registry, but other software does probably not.
> Require oemof.network v0.4

- src/oemof/solph/components/_generic_storage.py
The length of the time steps is given in hours. Thus, the old explanation was at least misleading.
> Fix doc of GenericStorage

- tox.ini
Testing via `tox -e "py39"` did not work due to an error with pytest_travis_fold.
This PR removes the dependency, as we do not use travis anymore.
> Remove pytest travis fold

- src/oemof/solph/components/_generic_storage.py
Make keyword arguments explicit in generic storage component.
Error message for kwargs not removed.
> Make kwargs explicit in storage

- src/oemof/solph/components/experimental/_sink_dsm.py
- tests/constraint_tests.py
- tests/lp_files/dsm_module_DLR_delay_time.lp
This enables to directly pass an iterable (usually) a list to the `delay_time` attribute of the experimental `SinkDSM`.
Instead of passing an integer, this allows to exclude some delay times which might be desired in order to limit model complexity which grows with longer delay times, see #903. 
Closes #903
> Allow SinkDSM's delay_time to be an iterable for approach 'DSM'

- src/oemof/solph/components/_generic_storage.py
GenericStorage is a component. Its definition resides in the module components. However, it inherits directly from Node.
This PR fixes that by letting GenericStorage inherit from network.Component.
I checked: All other components do inherit in some way from Component.
> Let GenericStorage inherit from network.Component

- docs/reference/oemof.solph.constraints.rst
- docs/whatsnew/v0-5-1.rst
- examples/storage_level_constraint/storage_level_constraint.py
- src/oemof/solph/_energy_system.py
- src/oemof/solph/constraints/__init__.py
- src/oemof/solph/constraints/storage_level.py
- tests/constraint_tests.py
- tests/lp_files/storage_level_constraint.lp
**From the example**
```Python
storage_level_constraint(
model=model,
name="multiplexer",
storage_component=storage,
multiplexer_bus=multiplexer,
input_levels={in_1: 1 / 3},  # in_0 is always active
output_levels={out_0: 1 / 6, out_1: 1 / 2},
)
```
There are two inflows (one always active, one active if storage level < 1/3) and two outflows (one active if storage level > 1/6 the second if storage level > 1/2). There is revenue for the outputs, the constraint inflow is free, the unconstraint one costs more than the revenue.
As the storage has losses, the outflows are used to empty it as fast as possible. It is held above the limit for the free inflow so that it can be used to recharge in the end. As the free inflow is constraint, the costly has to kick in in the end to fully recharge the …
> Add storage_level_constraint

- src/oemof/solph/_energy_system.py
The method implemented here seems to be more robust and is probably also more comprehensible.
Side note: I had a problem when creating the needed time intervals from the index of a DataFrame, where the original version did not work. The new implementation now works.
> Fix creation of time intervals from time index

- src/oemof/solph/components/experimental/_sink_dsm.py
- tests/lp_files/dsm_module_DLR_invest_multi_period.lp
This PR fixes one constraint formulation in the `SinkDSMDLRInvestmentBlock`. I was meaning to impose a periodical limit on shedding, but forgot to adjust it, resulting in an overall limit that did not make any sense. Now it is fixed.
Please review, @p-snft and if okay, feel free to merge back.
> Fix SinkDSM load shedding limit

- setup.cfg
setup.cfg named outdated versions of Python. This PR fixes that so that it is aligned with setup.py.
> Fix Python versions in setup.cfg

- src/oemof/solph/components/_link.py
- tests/test_warnings.py
close #949
Due to the process of building oemof.tabular.facades, it's necessary that the Link component uses its default values during its instantiation, as no values are passed. These default values are updated afterward.
Therefore, I will add None as default values for the explicit arguments and add a warning for this case.
> Set arguments defaults in link

- docs/requirements.txt
Starting Aughust 29th, readthedocs does not provide system-wide Python packages any more, so we need to add the dependencies explicitly.
> Prepare for changes at readthedocs

- src/oemof/solph/components/_generic_storage.py
- tests/lp_files/connect_investment_multi_period.lp
- tests/lp_files/periodical_investment_limit.lp
- tests/lp_files/storage_invest_1_multi_period.lp
- tests/lp_files/storage_invest_2_multi_period.lp
- tests/lp_files/storage_invest_3_multi_period.lp
- tests/lp_files/storage_invest_4_multi_period.lp
- tests/lp_files/storage_invest_5_multi_period.lp
- tests/lp_files/storage_invest_6_multi_period.lp
- tests/lp_files/storage_invest_all_nonconvex_multi_period.lp
- tests/lp_files/storage_invest_minimum_multi_period.lp
- tests/lp_files/storage_invest_multi_period.lp
- tests/lp_files/storage_invest_with_offset_multi_period.lp
- tests/lp_files/storage_invest_without_offset_multi_period.lp
- tests/multi_period_constraint_tests.py
- tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_investment_model.py
Add a constraint to force initial storage level to 0 in case of multi-period investment modelling to prevent storage from being filled without any associated costs in case of investments in the first period.
> Define multi-period investment storage level for very first time step of optimization

- examples/storage_costs/storage_costs.py
- src/oemof/solph/components/_generic_storage.py
- tests/constraint_tests.py
- tests/lp_files/storage.lp
Implement parameter `storage_costs` for `GenericStorage`: `storage_costs` might exist, e.g. if space can be rented depending on the stored energy. So, this might be seen as an alternative to investment optimisation. A second use case is to incentivise using the storage in the last time step if the storage is not periodic. This can be done by giving `storage_costs=n_time_steps * [0] + [-energy_price]`, so that stored energy in the last time step is valued with the energy price.
> Add storage_costs to GenericStorage

- docs/whatsnew/v0-5-2.rst
- src/oemof/solph/processing.py
* Fix "Flow" does not have "_in_edges"
> Adapt to cleaned up oemof.network

- src/oemof/solph/components/_generic_storage.py
The __init__ method was malfunctioning with the preferred way to declare investments in the attr nominal_storage_capacity. Probably due to code legacy from older versions.
The investment and nominal_storage_capacity attributes were mixed together and assigned in different parts of the initialization.
> BUGFIX: GenericStorage investment initialization

- docs/usage.rst
- docs/whatsnew/v0-5-1.rst
- src/oemof/solph/_energy_system.py
- src/oemof/solph/_options.py
- src/oemof/solph/flows/_investment_flow_block.py
* Correct the type of `periods` attribute of an energy system to list.
* Add hint to usage of `timeincrement` in combination with `timeindex`.
* Provide minor doc fixes alongside.
> Fix outdated multi-period usage docs

- docs/usage.rst
- docs/whatsnew/v0-5-2.rst
- src/oemof/solph/_energy_system.py
- src/oemof/solph/components/_generic_storage.py
- src/oemof/solph/components/experimental/_sink_dsm.py
- src/oemof/solph/flows/_investment_flow_block.py
- tests/lp_files/dsm_module_DIW_invest_multi_period_remaining_value.lp
- tests/lp_files/dsm_module_DLR_invest_multi_period_remaining_value.lp
- tests/lp_files/dsm_module_oemof_invest_multi_period_remaining_value.lp
- tests/lp_files/linear_converter_invest_multi_period_remaining_value.lp
- tests/lp_files/storage_invest_1_multi_period_remaining_value.lp
- tests/multi_period_constraint_tests.py
This PR extends #982 
It actually allows for compating the original value of an asset vs. the remaining one and allows for the consideration of changes in investment expenses over time.
In order not to force this as a default behaviour, a boolean switch has been included to switch the functionality on or off as desired.
> Compare differences in remaining value vs. actual value

- src/oemof/solph/components/experimental/_generic_caes.py
- tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py
Remove the obsolete `fixed_costs` parameter for instances of the `GenericCAES` which does not (resp. no longer?) support it.
Closes #994
> Remove obsolete fixed costs parameter for GenericCAES initialization

- src/oemof/solph/components/_offset_converter.py
- tests/lp_files/offsetconverter.lp
- tests/lp_files/offsetconverter_multi_period.lp
- tests/lp_files/offsetconverter_nonconvex.lp
- tests/lp_files/offsetconverter_nonconvex_investment.lp
Fixes the `OffsetConverter` to work as documented.
Closes #1010
> Fix y intercept of OffsetConverter

- examples/storage_investment/v1_invest_optimize_all_technologies.py
- examples/storage_investment/v2_invest_optimize_only_gas_and_storage.py
- examples/storage_investment/v3_invest_optimize_only_storage_with_fossil_share.py
- examples/storage_investment/v4_invest_optimize_all_technologies_with_fossil_share.py
Closes #1014
* Fixes errouneous usage of `nominal_capacity` instead of `nominal_storage_capacity` for storage examples.
* Replaces `investment` attribute for example v4 as this is the upcoming standard.
> Fix / update storage investment examples

- .github/workflows/packaging.yml
- .github/workflows/tox_checks.yml
- tox.ini
Direct invocation of `setup.py` seems to be long deprecated (e.g. https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), it can be replaced with the `build` package.
> Replace setup.py invocation by build

- docs/whatsnew/v0-5-2.rst
- src/oemof/solph/components/_generic_storage.py
- src/oemof/solph/components/experimental/_sink_dsm.py
- src/oemof/solph/flows/_investment_flow_block.py
- tests/lp_files/converter_invest_multi_period.lp
- tests/lp_files/dsm_module_DIW_invest_multi_period.lp
- tests/lp_files/dsm_module_DIW_invest_multi_period_remaining_value.lp
- tests/lp_files/dsm_module_DLR_invest_multi_period.lp
- tests/lp_files/dsm_module_DLR_invest_multi_period_remaining_value.lp
- tests/lp_files/dsm_module_oemof_extended.lp
- tests/lp_files/dsm_module_oemof_invest_multi_period.lp
- tests/lp_files/dsm_module_oemof_invest_multi_period_remaining_value.lp
- tests/lp_files/multi_period_period_length.lp
- tests/lp_files/storage_invest_multi_period.lp
- tests/multi_period_constraint_tests.py
close #1019
Remove duplicated discounting for fixed costs.
The discounting is already taken care of as the discount starts with the temporal distance of optimization start and investment period.
> Remove duplicated discounting

- .bumpversion.cfg
- .github/workflows/lint.yml
- .github/workflows/packaging.yml
- .github/workflows/tox_checks.yml
- .github/workflows/tox_pytests.yml
- MANIFEST.in
- VERSION
- docs/conf.py
- pyproject.toml
- setup.cfg
- setup.py
- src/oemof/solph/__init__.py
- src/oemof/solph/constraints/equate_variables.py
- src/oemof/solph/constraints/integral_limit.py
- src/oemof/solph/constraints/investment_limit.py
- src/oemof/solph/constraints/shared_limit.py
- tests/constraint_tests.py
- tests/multi_period_constraint_tests.py
- tests/test_components.py
- tests/test_energy_system.py
- tests/test_models.py
- tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_dispatch_model.py
- tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_investment_model.py
- tests/test_time_index.py
This also adds explicit tests for the warnings that are now silenced.
> Fix warnings

- docs/whatsnew/v0-5-3.rst
- src/oemof/solph/components/_generic_chp.py
- src/oemof/solph/components/_offset_converter.py
- src/oemof/solph/components/_sink.py
- src/oemof/solph/components/_source.py
This fixes #1059 by explicitly passing `custom_attributes` to the base class instead of unpacking them.
> Explicitely pass `custom_properties` to `Node` class

- docs/usage.rst
- docs/whatsnew/v0-5-3.rst
- examples/offset_converter_example/offset_diesel_genset_nonconvex_investment.py
- src/oemof/solph/components/_offset_converter.py
- tests/constraint_tests.py
- tests/multi_period_constraint_tests.py
- tests/test_components.py
This PR enables the OffsetConverter to output two (or more) flows with part-load depending efficiencies.
1. `outputs` are allowed to contain multiple busses.
2. `coefficients` expects a dictionary, where the keys are the output busses and the values are the tuples containing the necessary parameters. I took the liberty to implement a deprecation warning for the old behaviour (passing a tuple without specifying the output bus it corresponds to). This way, the OffsetConverter is more in line with the regular Converter and there is less room for confusion. But this is totally up for debate!
3. The issues discussed in https://github.com/oemof/oemof-solph/issues/1010 are fixed (misleading docu, usage guide and erroneous example).
> Multiple Outputs for OffsetConverter

- src/oemof/solph/components/_generic_storage.py
Code checked if investment and nominal_value are both given. As investment is now handed to nominal value, this can no longer happen.
> Delete unreachable code

- docs/whatsnew/v0-5-4.rst
- src/oemof/solph/components/_sink.py
- src/oemof/solph/components/_source.py
- tests/test_components/test_sink.py
- tests/test_components/test_source.py
- tests/test_warnings.py
There was a warning and a comment that having multiple inputs/outputs for one Sink/Source is unintended but should be possible. I think we can remove that "strong recommendation" as it just works.
To not let beginners fall into the trap of having a dangling Sink or Source, like the old warning also might have prevented, inputs and outputs are now explicitly named arguments without a default.
> Allow sinks/sources to have multiple inputs/outputs

- examples/storage_balanced_unbalanced/storage.py
- src/oemof/solph/components/_generic_storage.py
- tests/lp_files/nonequidistant_timeindex.lp
- tests/lp_files/shared_limit.lp
- tests/lp_files/shared_limit_multi_period.lp
- tests/lp_files/storage.lp
- tests/lp_files/storage_fixed_losses.lp
- tests/lp_files/storage_fixed_losses_multi_period.lp
- tests/lp_files/storage_invest_3.lp
- tests/lp_files/storage_invest_3_multi_period.lp
- tests/lp_files/storage_invest_5.lp
- tests/lp_files/storage_invest_5_multi_period.lp
- tests/lp_files/storage_level_constraint.lp
- tests/lp_files/storage_multi_period.lp
- tests/lp_files/storage_unbalanced.lp
- tests/lp_files/storage_unbalanced_multi_period.lp
- tests/test_components/test_storage.py
- tests/test_options.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py
I think it makes a lot of sense, e.g. for adding custom constraints, to have an explicit variable for the losses of the storage. Note that the formula for the relative lasses is more complicated
```
losses(t) = energy(t) * (1-(1-b)**tau))
energy(t+1)= energy(t)-losses(t)
``` 
vs
```
energy(t+1) = energy(t) * (1-b)**tau
```
but I think the additional variable and constraint is useful and the 1-(1-b)**tau instead of (1-b)**tau changes a value in the lp file, so it will not significantly increase computational time.
PS: I existentially pushed this change to dev, so this PR reverts the revert.
> Introduce variable for storage losses

- docs/whatsnew/v0-5-4.rst
- src/oemof/solph/_plumbing.py
- src/oemof/solph/components/_generic_storage.py
- src/oemof/solph/components/_offset_converter.py
- src/oemof/solph/flows/_flow.py
- src/oemof/solph/flows/_investment_flow_block.py
- src/oemof/solph/flows/_non_convex_flow_block.py
- src/oemof/solph/processing.py
- tests/test_plumbing.py
- tests/test_scripts/test_solph/test_variable_chp/test_variable_chp.py
The auto-stretch feature of the _Sequence contained hidden magic, as it tracked the last "entry" that has been accessed and pretended to have a length based on this. So, outcomes depend on something that is assumed to be a read access. Also, self.data was erived from UserList but never really supported all of the expected functionality in a consistent way.
The new _FakeSequence is a lot simpler. In particular it has an explicit (fake) length that needs to be set before casting to (stretched) lists. The default length is not set, because member functions using the same names as in `numpy.array` can help to work without an iterator.
Fixes #1100.
> Replace _Sequence by _FakeSequence

- src/oemof/solph/constraints/integral_limit.py
- tests/constraint_tests.py
- tests/lp_files/emission_budget_limit.lp
- tests/lp_files/emission_limit.lp
- tests/lp_files/emission_limit_lower.lp
- tests/lp_files/emission_limit_no_error.lp
- tests/test_constraints_module.py
If it's possible to give an upper limit, a lower limit should also be posible.
> Allow lower limit for generic_integral_limit

- src/oemof/solph/flows/_flow.py
This way, it should be much easier to understand.
> Formulate full_load_time docstring specific for energy

- docs/whatsnew/v0-6-0.rst
- src/oemof/solph/components/_converter.py
- src/oemof/solph/components/_extraction_turbine_chp.py
- src/oemof/solph/components/_generic_chp.py
- src/oemof/solph/components/_offset_converter.py
- src/oemof/solph/components/_sink.py
- src/oemof/solph/components/experimental/_sink_dsm.py
- tests/test_components/test_offset_converter.py
Setting the `oemof.network.Node.custom_properties` using an argument called `custom_attributes` was rather confusing. Additionally, the class Bus already called the argument `custom_properties`.
> Rename custom_attributes to custom_properties for Nodes

- src/oemof/solph/components/_generic_storage.py
This PR is merely a fix for the unrenderable storage balance docstring equation in GenericStorageBlock. Linebreaks and an ampersand were missing, which I added.
> Fix LaTeX code in docstring of GenericStorageBlock

- src/oemof/solph/_plumbing.py
- src/oemof/solph/components/_source.py
- src/oemof/solph/processing.py
- tests/test_outputlib/test_processing.py
- tests/test_plumbing.py
I ran into 2 problems while using `parameter_as_dict()` from the `processing` module.
1. Using `custom_attributes` / `custom_properties` in# `solph.components` with numeric values.
2. Using a number with a higher dimension in `sequences`, such as a DataFrame, or a nested list.
I added two failing test and fixed the issues
1. Number has not been taken account, only strings. I fixed this in the `processing` module.
2. Using higher dimensions has not caused problems in the model but in the `parameter_as_dict`. I noticed that after solving a model after 10 hours, so I added a check to raise the error directly and not at the end.
> Fix bugs in parameter as dict

- docs/usage.rst
- src/oemof/solph/components/_generic_storage.py
- tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
For some reason, `GenericStorageBlock.init_content` was still defined and (half way) used in some cases. This removes it, as we (should) just use `GenericStorageBlock.storage_content[n, m.TIMESTEPS.at(1)` instead.
Fixes #1176.
> Remove GenericStorageBlock.init_content

- AUTHORS.rst
- CITATION.cff
- src/oemof/solph/_options.py
- src/oemof/solph/flows/_invest_non_convex_flow_block.py
- tests/test_options.py
- tests/test_scripts/test_solph/test_non_convex_investment_offset/test_non_convex_investment_offset.py
**General description**
This pull request aims to fix the issue #1172 
To fix the bug @jfreissmann and I expand the `_create_sets` method in the `_invest_non_convex_flow_block`. We decitde to name the sets linear and offset not to repeat the convetion of convex and nonconvex. But you can feel free to change those.
<details><summary>_create_sets method</summary>
```python
self.LINEAR_INVEST_NON_CONVEX_FLOWS = Set(
initialize=[
(g[0], g[1])
for g in group
if g[2].investment.nonconvex is None
]
)
self.OFFSET_INVEST_NON_CONVEX_FLOWS = Set(
initialize=[
(g[0], g[1])
for g in group
if isinstance(g[2].investment.nonconvex, NonConvex)
]
)
```
</details>
After that we expand the `_investvar_bound_rule` to differentiate between the linear and offset flows. In addition, we create the `invest_status` …
> Fix bug where InvestNonConvexFlowBlock does not eliminate Investment offset when no investment is made

- src/oemof/solph/_options.py
- src/oemof/solph/flows/_invest_non_convex_flow_block.py
- tests/test_components/test_storage.py
- tests/test_options.py
- tests/test_scripts/test_solph/test_non_convex_investment_offset/test_non_convex_investment_offset.py
The current set definitions of the `InvestNonConvexFlowBlock`, as implemented by our PR #1173, check wether the argument passed to the `nonconvex` parameter is an instance of the `solph._options.NonConvex` class. This is not the intended usage of the `nonconvex` parameter of the `solph._options.Investment` class. This PR aligns the set definition to check for boolean values `True` or `False`. A test added in the PR mentioned above also contains the erroneous usage, which is fixed as well.
Additionally, @maltefritz and I added a type check of the `nonconvex` argument, as its misaligned usage in contrast to the Flow's `nonconvex` parameter can lead to wrong usage staying undetected. A test for the check is added as well.
This should also help resolve Issue #1179.
> Fix InvestNonConvexFlowBlock set definition by nonconvex parameter

- src/oemof/solph/components/_generic_storage.py
- src/oemof/solph/constraints/storage_level.py
- src/oemof/solph/processing.py
I stumbled over intra/inter so often that I want to have clearly distinguishable names.
> Rename storage content variables

- src/oemof/solph/_results.py
This changes the results object to be able to handle variables with the same name (present in different Blocks) as long as the indexes are disjunct.
Analysis of the situation:
* We have the convention that one Entity (Node or Flow) is only covered by one Block.
* The status of a Flow is defined either in NonConvexFlowBlock or in InvestNonConvexFlowBlock. As the function _create(self, group=None) is not called by the Constructor, the variable exists only once per Flow.
> Allow local variable names for Results
